version: '3'
services:
  api:
    build:
      context: .
      dockerfile: DockerFile
    ports:
      - "1080:1080"
    depends_on:
      - redis
  redis:
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
